#@TYPE: Machine
#@NAME: StarSBC
#@SOC: i.MX6ULL
#@DESCRIPTION: Machine configuration for Somlabs StarSBC
#@MAINTAINER: Marcin Bober <mbober1@gmail.com>

MACHINEOVERRIDES =. "mx6ull:"

include conf/machine/include/imx-base.inc
include conf/machine/include/arm/armv7a/tune-cortexa7.inc

UBOOT_MAKE_TARGET = "u-boot.imx"
UBOOT_SUFFIX = "imx"

PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"
UBOOT_CONFIG = "sd"
UBOOT_CONFIG[sd] = "somlabs_visionsom_6ull_defconfig,sdcard"

KERNEL_DEVICETREE = "nxp/imx/starsbc-6ull.dtb"

WKS_FILE = "custom_partitions.wks.in"
KERNEL_MODULE_AUTOLOAD += "g_ether"

IMAGE_BOOT_FILES = "boot.scr"
IMAGE_FSTYPES:append = " ext4"

MACHINE_FEATURES += "wifi"
MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-murata-1dx"