MACHINEOVERRIDES =. "mx6:mx6ul:mx6ull:"

require conf/machine/include/imx-base.inc
require conf/machine/include/arm/armv7a/tune-cortexa7.inc

IMAGE_FSTYPES = "wic.zst tar.zst"

UBOOT_CONFIG = "sd"
UBOOT_CONFIG[sd] = "starsbc_6ull_defconfig,sdcard"
UBOOT_DTB_NAME = "imx6ull-somlabs-starsbc.dtb"

PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-imx"

SERIAL_CONSOLES = "115200;ttymxc0"

IMAGE_BOOT_FILES = " \
        ${KERNEL_IMAGETYPE} \
        ${@make_dtb_boot_files(d)} \
"

KERNEL_DEVICETREE = "starsbc-6ull-custom.dtb"

MACHINE_FEATURES += "wifi bluetooth bcm43430 rtc"
MACHINE_FEATURES:remove = "acpi pci wifi bluetooth qemu-usermode screen touchscreen"

BCM_FIRMWARE_SUFFIX = "somlabs,starsbc-6ull"
KERNEL_MODULE_AUTOLOAD += "g_ether"
WKS_FILE = "custom_partitions.wks.in"
